/*
 *  ======== config.c ========
 *  Configuration-specific definitions
 *
 *  DO NOT EDIT - This file is generated by the SysConfig tool for
 *  the TI Sensors in this application.
 */
#include <stdint.h>
#include <stdio.h>

#include "INA740.h"

#include "config.h"
#include "hardware/i2c.h"

/*
 *  ======== INA740_0 ========
 *  INA740 Sensor configuration settings
 */

static INA740_State INA740_0_state = {

    /* Configuration and Settings */
    .configRegister = (INA740_config_register_rst_NormalOperation | \
                       INA740_config_register_rstacc_NormalOperation | \
                       0x0000U),
    .adcConfigRegister = (INA740_adc_config_register_mode_Continuoustemperaturecurrentandbusvoltage | \
                          INA740_adc_config_register_vbusct_1052us | \
                          INA740_adc_config_register_vsenct_1052us | \
                          INA740_adc_config_register_tct_1052us | \
                          INA740_adc_config_register_avg_1),
    .alertDiagRegister = (INA740_alert_diag_register_alatch_Transparent | \
                          INA740_alert_diag_register_cnvr_DisableconversionreadyflagonALERTpin | \
                          INA740_alert_diag_register_slowalert_ALERTcomparisononnonaveragedADCvalue | \
                          INA740_alert_diag_register_apol_Normalactivelowopendrain),
    .colRegister = 0x7FFFU,
    .culRegister = 0x8000U,
    .bovlRegister = 0x7FFFU,
    .buvlRegister = 0x0000U,
    .tempLimitRegister = 0x7FF0U,
    .pwrLimitRegister = 0xFFFFU,


    /* Sensor's I2C bus ID and address */
    .busId = 1,
    .devAddr = 0x40U,

};
const INA740_Handle INA740_0 = &INA740_0_state;


