/*
 *  ======== INA740.c ========
 *  INA740 APIs for initialization and use of the INA740 peripheral
 *
 *  DO NOT EDIT - This file is generated by the SysConfig tool for
 *  the TI Sensors in this application.
 */

#include <stddef.h>
#include <stdint.h>

#include "INA740.h"
#include "mcu.h"


#define MSB(u16) (((u16) & 0xFF00U) >> 8)
#define LSB(u16) ((u16) & 0xFFU)

#define maxRegAddress 0x3F

// Register size in bytes
const uint8_t INA740_regSize[maxRegAddress+1] = {
                                            2,2,0,0,0,2,2,2,\
                                            3,5,5,2,2,2,2,2,\
                                            2,2,0,0,0,0,0,0,\
                                            0,0,0,0,0,0,0,0,\
                                            0,0,0,0,0,0,0,0,\
                                            0,0,0,0,0,0,0,0,\
                                            0,0,0,0,0,0,0,0,\
                                            0,0,0,0,0,0,2,2
};

/*
 *  ======== INA740_writeReg ========
 * Write register
 */
void INA740_writeReg(INA740_Handle sensor, uint8_t regAddr, uint16_t value)
{
    uint8_t txBuf[3] = {0}; //All writable registers are 2 bytes

    txBuf[0] = regAddr;
    txBuf[1] = MSB(value);
    txBuf[2] = LSB(value);
    mcu_i2cTransfer(sensor->busId, sensor->devAddr, txBuf, 3, NULL, 0);
}

/*
 *  ======== INA740_config ========
 * Configure device with current settings.
 */
void INA740_config(INA740_Handle sensor)
{
    //Initialize the bus containing this sensor
    mcu_i2cInit(sensor->busId);

    //Write sensor Configuration Registers
    INA740_writeReg(sensor, INA740_config_register, sensor->configRegister);
    INA740_writeReg(sensor, INA740_adc_config_register, sensor->adcConfigRegister);
    INA740_writeReg(sensor, INA740_alert_diag_register, sensor->alertDiagRegister);
    INA740_writeReg(sensor, INA740_col_register, sensor->colRegister);
    INA740_writeReg(sensor, INA740_cul_register, sensor->culRegister);
    INA740_writeReg(sensor, INA740_bovl_register, sensor->bovlRegister);
    INA740_writeReg(sensor, INA740_buvl_register, sensor->buvlRegister);
    INA740_writeReg(sensor, INA740_temp_limit_register, sensor->tempLimitRegister);
    INA740_writeReg(sensor, INA740_pwr_limit_register, sensor->pwrLimitRegister);

}

/*
 *  ======== INA740_readReg ========
 *  Read register
 */
uint64_t INA740_readReg(INA740_Handle sensor, uint8_t regAddr)
{
    uint64_t value;
    int i;
    
    uint8_t txBuf[1] = {0};
    uint8_t rxBuf[5] = {0}; //max buffer size

    txBuf[0] = regAddr;

    //Read register
    mcu_i2cTransfer(sensor->busId, sensor->devAddr, txBuf, 1, rxBuf, INA740_regSize[regAddr]);

    //Combine bytes
    value = rxBuf[0];
    for(i = 1; i < INA740_regSize[regAddr]; i++)
    {
        value = (value << 8) | rxBuf[i];
    }

    return value;
}

/*
 *  ======== INA740_getVBUS_V ========
 *  Get VBUS value (V)
 */
float INA740_getVBUS_V(INA740_Handle sensor)
{
    uint64_t value = INA740_readReg(sensor, INA740_vbus_register);
    float data;

    //Convert for 2's compliment and signed value (though always positive)
    if(value > 0x7FFF)
    {
        data = (float)value - 0x10000; //left for redundancy and error checking, should never get used
    }
    else
    {
        data = (float)value;
    }

    //Convert to V
    data = (data * 3.125) / 1000;

    return data;
}

/*
 *  ======== INA740_getDIETEMP_C ========
 *  Get DIETMEP value (C)
 */
float INA740_getDIETEMP_C(INA740_Handle sensor)
{
    uint64_t value = INA740_readReg(sensor, INA740_dietemp_register);
    float data;

    //Remove reserved bits
    value = value >> 4;

    //Convert for 2's compliment and signed value
    if(value > 0x7FF)
    {
        data = (float)value - 0x1000; 
    }
    else
    {
        data = (float)value;
    }

    //Convert to C
    data = (data * 125) / 1000;

    return data;
}

/*
 *  ======== INA740_getDIETEMP_F ========
 *  Get DIETMEP value (F)
 */
float INA740_getDIETEMP_F(INA740_Handle sensor)
{
    float data = INA740_getDIETEMP_C(sensor);
    
    //Convert to F
    data = (data * (9/5)) + 32;

    return data;
}

/*
 *  ======== INA740_getCURRENT_A ========
 *  Get CURRENT value (A)
 */
float INA740_getCURRENT_A(INA740_Handle sensor)
{
    uint64_t value = INA740_readReg(sensor, INA740_current_register);
    float data;

    //Convert for 2's compliment and signed value 
    if(value > 0x7FFF)
    {
        data = (float)value - 0x10000;
    }
    else
    {
        data = (float)value;
    }

    data = data * 1.2 / 1000;

    return data;
}

/*
 *  ======== INA740_getPOWER_W ========
 *  Get POWER value (W)
 */
float INA740_getPOWER_W(INA740_Handle sensor)
{
    uint64_t value = INA740_readReg(sensor, INA740_power_register);
    float data;

    data = (float)value * 1.2 / 1000 * 0.2;

    return data;
}

/*
 *  ======== INA740_getENERGY_J ========
 *  Get ENERGY value (J)
 */
double INA740_getENERGY_J(INA740_Handle sensor)
{
    uint64_t value = INA740_readReg(sensor, INA740_energy_register);
    double data;

    data = (double)value * 1.2 / 1000 * 0.2 *16;

    return data;
}

/*
 *  ======== INA740_getCHARGE_C ========
 *  Get CHARGE value (C)
 */
double INA740_getCHARGE_C(INA740_Handle sensor)
{
    uint64_t value = INA740_readReg(sensor, INA740_charge_register);
    double data;

    //Convert for 2's compliment and signed value 
    if(value > 0x7FFFFFFFFF)
    {
        data = (double)value - 0x10000000000;
    }
    else
    {
        data = (double)value;
    }

    data = data * 1.2 / 1000 / 16;

    return data;
}